config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers:  { omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations' }

  root 'products#index'

  resources :products do
    collection do
      get 'search'
      post '/:id/pay' => 'products#pay', as: 'pay'
      get '/:id/user_buying' => 'products#user_buying'
      get '/get_category_children' => 'products#get_category_children', defaults: { format: 'json' }
      get '/get_category_grandchildren' => 'products#get_category_grandchildren', defaults: { format: 'json' }
      get '/:parent_id/category_search_parent' => 'products#category_search_parent'
      get '/:parent_id/:child_id/category_search_child' => 'products#category_search_child'
      get '/:parent_id/:child_id/:grandchild_id/category_search_grandchild' => 'products#category_search_grandchild'
    end
  end

  resources :users ,only: [:show] do
    collection do
      get '/:id/logout' => 'users#logout'
      get '/:id/credit' => 'users#credit'
      get '/:id/credit_add' => 'users#credit_add'
      get '/:id/profile_edit' => 'users#profile_edit'
      get '/:id/user_check' => 'users#user_check'
      get '/:id/appear_notice' => 'users#appear_notice'
      get '/:id/appear_todo' => 'users#appear_todo'
      get '/:id/appear_transation' => 'users#appear_transation'
      get '/:id/appear_after_transation' => 'users#appear_after_transation'    
    end
  end

  resources :signup, only: [:create] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'step5'
      get 'step6'
      get 'done'
    end
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  has_one :detail, dependent: :destroy
  accepts_nested_attributes_for :detail
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  belongs_to :category

  
  validates :name, presence: true,length: { minimum: 1, maximum: 40 }
  validates :discription, presence: true,length: { minimum: 1, maximum: 1000 }
  validates :condition, presence: true
  validates :delivery_charge, presence: true
  validates :origin_area, presence: true
  validates :days_left_send, presence: true
  validates :price, 
            presence: true,
            numericality: { only_integer: true,  greater_than: 299, less_than: 10000000}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :user_buying, :update, :edit, :destroy, :pay,]

  def index
    @product = Product.new
    @category_parent = Category.where(ancestry: nil)

    @rady_products = []
    rady_category = Detail.where(large_category: "レディース").limit(10).order("id DESC")
    rady_category.each do |category|
      @rady_products << Product.find(category.product_id)
    end

    @men_products = []
    men_category = Detail.where(large_category: "メンズ").limit(10).order("id DESC")
    men_category.each do |category|
      @men_products << Product.find(category.product_id)
    end

    @machine_products = []
    machine_category = Detail.where(large_category: "家電・スマホ・カメラ").limit(10).order("id DESC")
    machine_category.each do |category|
      @machine_products << Product.find(category.product_id)
    end

    @hoby_products = []
    hoby_category = Detail.where(large_category: "おもちゃ・ホビー・グッズ").limit(10).order("id DESC")
    hoby_category.each do |category|
      @hoby_products << Product.find(category.product_id)
    end
  end

  def new
    @product = Product.new
    @product.images.build
    @product.build_detail
  end
  
  def create
    @product = Product.new(
      name: product_params[:name],
      discription: product_params[:discription],
      condition: product_params[:condition],
      delivery_charge: product_params[:delivery_charge],
      days_left_send: product_params[:days_left_send],
      origin_area: product_params[:origin_area],
      price: product_params[:price],
      user_id: current_user.id,
      status: "出品中"
      )
    @product.build_detail(
      large_category: product_params[:detail_attributes][:large_category],
      medium_category: product_params[:detail_attributes][:medium_category],
      small_category: product_params[:detail_attributes][:small_category]
    )

    if params[:images].present?
      params[:images][:img].each do |img|
        @product.images.build(img: img)
      end
    else
      @product.images.build(img: params[:images])
    end
    
    if @product.save
      redirect_to root_path
    else
      render "/products/new"
    end
  end 

  def show
    @category_parent = Category.where(ancestry: nil)
    @user_products = Product.where(user_id: @product.user_id).where.not(id: params[:id]).limit(6)

    product_large_categorys = Detail.where(large_category: @product.detail.large_category).where.not(product_id: params[:id]).limit(6)

    @product_parent = Category.find_by(name: @product.detail.large_category)
    if @product.detail.medium_category.present?
      @product_parent.children.each do |child|
        if child.name == @product.detail.medium_category
          @product_child = child
        end
      end
      if @product.detail.small_category.present?
        @product_child.children.each do |grandchild|
          if grandchild.name == @product.detail.small_category
            @product_grandchild = grandchild
          end
        end
      end
    end

    @category_products = []
    product_large_categorys.each do |category|
      @category_products << Product.find(category.product_id)
    end
  end

  def edit
    unless @product.user.id == current_user.id
      redirect_to "/products/#{@product.id}"
    end
    @product.images.build
  end

  def update
    if @product.user_id == current_user.id
      if params[:images].present?
        @product.images.each do |image|
          image.destroy
        end
        params[:images][:img].each do |img|
          @product.images.build(img: img)
        end
      end
      @product.update(product_params)
    end
    redirect_to "/products/#{@product.id}"
  end

  def destroy
    if @product.user.id == current_user.id
      @product.destroy
    end
    redirect_to "/"
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def category_search_parent
    @category_parent = Category.where(ancestry: nil)
    @large_category = Category.find(params[:parent_id])
    
    large_categorys = Detail.where(large_category: @large_category.name).limit(120)
    @large_category_products = []
    large_categorys.each do |category|
      @large_category_products << Product.find(category.product_id)
    end
  end

  def category_search_child
    @category_parent = Category.where(ancestry: nil)
    @large_category = Category.find(params[:parent_id])
    @medium_category = Category.find(params[:child_id])
    
    medium_categorys = Detail.where(large_category: @large_category.name, medium_category: @medium_category.name).limit(120)
    @medium_category_products = []
    medium_categorys.each do |category|
      @medium_category_products << Product.find(category.product_id)
    end
  end

  def category_search_grandchild
    @category_parent = Category.where(ancestry: nil)
    @large_category = Category.find(params[:parent_id])
    @medium_category = Category.find(params[:child_id])
    @small_category = Category.find(params[:grandchild_id])
    
    small_categorys = Detail.where(large_category: @large_category.name, medium_category: @medium_category.name, small_category: @small_category.name).limit(120)
    @small_category_products = []
    small_categorys.each do |category|
      @small_category_products << Product.find(category.product_id)
    end
  end

  def search
    @keyword = params[:keyword]
    @products = Product.where('name LIKE(?)',"%#{@keyword}%").limit(120).order("id DESC")
    @all_products = Product.all.order("id DESC")
  end

  def user_buying
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
    
  def pay
    Payjp.api_key = Rails.application.credentials.PAYJPSK
    charge = Payjp::Charge.create(
    :amount => @product.price,
    :card => params['payjp-token'],
    :currency => 'jpy',
    )
    @product.status = "取引中"
    @product.buyer_id = current_user.id
    @product.save
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
    :name, 
    :discription, 
    :condition, 
    :delivery_charge, 
    :days_left_send,
    :origin_area,
    :price,
    detail_attributes:[:id, :large_category, :medium_category, :small_category]
    )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_detail_error_messages.html.haml
- if detail.errors.any?
  - unless detail.valid?
    - if errors = detail.errors.full_messages_for(column.to_sym)
      %ul.error-messages
        - errors.each do |error|
          %li.error-message= error

app/views/products/_image_error_messages.html.haml
- images.each do |image|
  - if image.errors.any?
    - unless image.valid?
      - if errors = image.errors.full_messages_for(column.to_sym)
        %ul.error-messages
          - errors.each do |error|
            %li.error-message= error

app/views/products/_product_error_messages.html.haml
- if product.errors.any?
  - unless product.valid?
    - if errors = product.errors.full_messages_for(column.to_sym)
      %ul.error-messages
        - errors.each do |error|
          %li.error-message= error

app/views/products/category_search_child.html.haml
= render "shared/top_header"
.header-mypage-ribon
  = link_to "/" do
    メルカリ
  &nbsp;＞&nbsp;
  = link_to "/products/#{@large_category.id}/category_search_parent" do
    = @large_category.name
  &nbsp;＞&nbsp;
  = @medium_category.name

.top-products
  .top-products__ancestry
    - @medium_category.children.each do |grandchild|
      = link_to "/products/#{@large_category.id}/#{@medium_category.id}/#{grandchild.id}/category_search_grandchild" do
        = grandchild.name
      &nbsp;
  .top-products__title-1
    = @medium_category.name
    の商品一覧
  .top-products__items
    - @medium_category_products.each do |product|
      = link_to product_path(product.id) do
        .top-products__items__item
          = image_tag product.images[0].img.url
          - if product.status !=  "出品中"
            .top-products__items__item__sold__image
            .top-products__items__item__sold__text SOLD
          .top-products__items__item__price
            ¥
            = product.price
          .top-products__items__item__name
            = product.name

= render "shared/top_footer"

app/views/products/category_search_grandchild.html.haml
= render "shared/top_header"
.header-mypage-ribon
  = link_to "/" do
    メルカリ
  &nbsp;＞&nbsp;
  = link_to "/products/#{@large_category.id}/category_search_parent" do
    = @large_category.name
  &nbsp;＞&nbsp;
  = link_to "/products/#{@large_category.id}/#{@medium_category.id}/category_search_child" do
    = @medium_category.name
  &nbsp;＞&nbsp;
  = @small_category.name

.top-products
  .top-products__ancestry
  .top-products__title-1
    = @small_category.name
    の商品一覧
  .top-products__items
    - @small_category_products.each do |product|
      = link_to product_path(product.id) do
        .top-products__items__item
          = image_tag product.images[0].img.url
          - if product.status !=  "出品中"
            .top-products__items__item__sold__image
            .top-products__items__item__sold__text SOLD
          .top-products__items__item__price
            ¥
            = product.price
          .top-products__items__item__name
            = product.name

= render "shared/top_footer"

app/views/products/category_search_parent.html.haml
= render "shared/top_header"
.header-mypage-ribon
  = link_to "/" do
    メルカリ
  &nbsp;＞&nbsp;
  = @large_category.name

.top-products
  .top-products__ancestry
    - @large_category.children.each do |child|
      = link_to "/products/#{@large_category.id}/#{child.id}/category_search_child" do
        = child.name
      &nbsp;
  .top-products__title-1
    = @large_category.name
    の商品一覧
  .top-products__items
    - @large_category_products.each do |product|
      = link_to product_path(product.id) do
        .top-products__items__item
          = image_tag product.images[0].img.url
          - if product.status !=  "出品中"
            .top-products__items__item__sold__image
            .top-products__items__item__sold__text SOLD
          .top-products__items__item__price
            ¥
            = product.price
          .top-products__items__item__name
            = product.name

= render "shared/top_footer"

app/views/products/edit.html.haml
.sale-page-title
  = link_to "/" do
    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2296184308", class: "sale-page-title--image"

.sale-page-box
  = form_for @product do |f|
    .sale-page-box__title
      商品の情報を入力
    .sale-page-box__upload-box
      .sale-page-box__upload-box__title
        = f.label :出品画像 
      .sale-page-box__upload-box__must
        必須
      .sale-page-box__upload-box__text
        最大10枚アップロードできます
      
      .sale-page-box__upload-box__item1
        .sale-page-box__upload-box__item1__preview1
        .sale-page-box__upload-box__item1__dropzone1
          %p クリックしてファイルをアップロード
          = f.fields_for :images do |i|
            = i.file_field :img, multiple: true, name: 'images[img][]', id: "upload-image", class: "upload-image", 'data-image': 0
      = render partial: 'image_error_messages', locals: {images: @product.images, column: "img"}

      .sale-page-box__upload-box__item2
        .sale-page-box__upload-box__item2__preview2
        .sale-page-box__upload-box__item2__dropzone2
          %p クリックしてファイルをアップロード

    .sale-page-box__product
      = f.label :商品名, class: "sale-page-box__product__title"
      .sale-page-box__product__must
        必須
      = f.text_field :name, class: "sale-page-box__product__form-name", placeholder: "商品名（必須 40字まで）"
      = render partial: 'product_error_messages', locals: {product: @product, column: "name"}

      = f.label :商品の説明, class: "sale-page-box__product__title"
      .sale-page-box__product__must
        必須
      = f.text_area :discription, class:"sale-page-box__product__form-text", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      = render partial: 'product_error_messages', locals: {product: @product, column: "discription"}

    .sale-page-box__pul
      .sale-page-box__pul__left
        商品の詳細

      .sale-page-box__pul__right
        .sale-page-box__pul__right__title
          カテゴリー
        .sale-page-box__pul__right__must
          必須
        .sale-page-box__pul__right__category
          = f.fields_for :detail do |i|
            = i.collection_select :large_category, Category.where(ancestry: nil), :name, :name, {prompt:'--'}, class: "sale-page-box__pul__right__category__parent"
            = render partial: 'detail_error_messages', locals: {detail: @product.detail, column: "large_category"}

        = f.label :商品の状態, class:"sale-page-box__pul__right__title"
        .sale-page-box__pul__right__must
          必須
        = f.select :condition, [["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], {prompt:"--"}, class: "sale-page-box__pul__right__not-margin"
        = render partial: 'product_error_messages', locals: {product: @product, column: "condition"}

    .sale-page-box__pul
      .sale-page-box__pul__left
        配送について
      .sale-page-box__pul__right
      
        = f.label :配送料の負担, class:"sale-page-box__pul__right__title"
        .sale-page-box__pul__right__must
          必須
        = f.select :delivery_charge, [["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]], {prompt:"--"}, class: "sale-page-box__pul__right__bottom-margin"
        = render partial: 'product_error_messages', locals: {product: @product, column: "delivery_charge"}

        = f.label :発送元の地域,  class:"sale-page-box__pul__right__title"
        .sale-page-box__pul__right__must
          必須
        = f.collection_select :origin_area, Prefecture.all,:name,:name, {prompt:'--'}, class: "sale-page-box__pul__right__bottom-margin"
        = render partial: 'product_error_messages', locals: {product: @product, column: "origin_area"}

        = f.label :発送までの日数, class:"sale-page-box__pul__right__title"
        .sale-page-box__pul__right__must
          必須
        = f.select :days_left_send, [["1~2日で配送","1~2日で配送"],["2~3日で配送","2~3日で配送"],["4~7日で配送","4~7日で配送"]], {prompt:"--"}, class: "sale-page-box__pul__right__bottom-margin"
        = render partial: 'product_error_messages', locals: {product: @product, column: "days_left_send"}

    .sale-page-box__price
      .sale-page-box__price__left
        販売価格（300〜9,999,999）
      .sale-page-box__price__right
        = f.label :価格, class: "sale-page-box__price__right__title"
        .sale-page-box__price__right__must
          必須
        .sale-page-box__price__right__en
          ¥
        = f.text_field :price, class: "sale-page-box__price__right__value", placeholder: "例）300"
        = render partial: 'product_error_messages', locals: {product: @product, column: "price"}

        .sale-page-box__price__right__fee
          販売手数料(10%)
          .minus
            ー
        .sale-page-box__price__right__profit
          販売利益
          .minus
            ー

    .sale-page-box__btn-box
      .sale-page-box__btn-box__text
        禁止されている出品、行為を必ずご確認ください。
        %br
        またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %br
        また、出品をもちまして加盟店規約に同意したことになります。
      = f.submit "変更する", class: "sale-page-box__btn-box__red-btn"
      .sale-page-box__btn-box__gray-btn
        もどる

.sale-page-footer
  %ul.sale-page-footer__box
    %li プライバシーポリシー
    %li メルカリ利用規約
    %li 特定商取引に関する表記
  .sale-page-footer__img
    = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2296184308", class: "sale-page-footer__img--logo"
  %p.sale-page-footer__rogo
    %small © 2019 Mercari

app/views/products/index.html.haml
= render "shared/top_page"

app/views/products/pay.html.haml
.done-top
  %header.user-buying__header
    %h1.user-buyinng__header__mercari-box
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2296184308", class: "user-buying__header__mercari-box__icon"
  .done-top__main
    .done-top__main__new
      %h2 購入完了
    .done-top__main__content
      .thanks
        .thank-you 購入が完了しました！
      = link_to "/", class: "done-btn" do
        .btn-red-done
          メルカリトップページに戻る

= render partial: 'signup/registration_footer'

app/views/products/search.html.haml
.top-header
  = link_to "/" do
    .top-header__logo
      = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"
  .top-header__search
    = form_tag("/products/search", method: :get) do 
      = text_field_tag :keyword, @keyword, class: "top-header__search__form", placeholder:"何かお探しですか？"

      = label :keyword, class: 'top-header__search__button' do
        = fa_icon "search", class: 'top-header__search__button'
        = submit_tag 'search', keyword: nil, class: "top-header__search__hidden"

  .top-header__list
    .top-header__list__category
      = fa_icon "list-ul"
      カテゴリーから探す
    .top-header__list__brand
      = fa_icon "tags"
      ブランドから探す

    - if user_signed_in?
      = link_to user_path(current_user.id) do
        .top-header__list__mypage
          マイページ

      = image_tag "user-mypage-icon.png", class: "header-image"

      .top-header__list__right-box
        = fa_icon "check", class: "header-icon"
        やることリスト

      .top-header__list__right-box
        = fa_icon "bell-o", class: "header-icon"
        おしらせ

      .top-header__list__right-box
        = fa_icon "heart-o", class: "header-icon"
        いいね！一覧

    - else
      = link_to new_user_session_path do
        .top-header__list__login
          ログイン

      = link_to step1_signup_index_path do
        .top-header__list__signup
          新規会員登録

.top-icon
  - if user_signed_in?
    = link_to new_product_path do
      .top-icon__margin
      .top-icon__text
        出品
      = fa_icon "camera"

  - else
    = link_to new_user_session_path do
      .top-icon__margin
      .top-icon__text
        出品
      = fa_icon "camera"

- if @products.length != 0 && @keyword.length != 0
  .top-search-products
    .top-search-products__head
      = @keyword
    .top-search-products__title
      の検索結果
    .top-search-products__num
      ="1~#{@products.count}件表示"
    .top-search-products__items
      - @products.each do |product|
        = link_to product_path(product.id) do
          .top-search-products__items__item
            = image_tag product.images[0].img.url
            - if product.status !=  "出品中"
              .top-products__items__item__sold__image
              .top-products__items__item__sold__text SOLD
            .top-search-products__items__item__price
              ¥
              = product.price
            .top-search-products__items__item__name
              = product.name

- elsif @keyword.length != 0
  .top-search-products
    .top-search-products__head
      = @keyword
    .top-search-products__title
      の検索結果はありません
    .top-search-products__num
      該当する商品が見つかりません。検索条件を変えて、再度お試しください。
    .top-search-products__new
      新着商品
    .top-search-products__items
      - @all_products.each do |product|
        = link_to product_path(product.id) do
          .top-search-products__items__item
            = image_tag product.images[0].img.url
            - if product.status !=  "出品中"
              .top-products__items__item__sold__image
              .top-products__items__item__sold__text SOLD
            .top-search-products__items__item__price
              ¥
              = product.price
            .top-search-products__items__item__name
              = product.name

- else
  .top-search-products
    .top-search-products__head
    .top-search-products__title
      検索結果はありません
    .top-search-products__num
      該当する商品が見つかりません。検索条件を変えて、再度お試しください。
    .top-search-products__new
      新着商品
    .top-search-products__items
      - @all_products.each do |product|
        = link_to product_path(product.id) do
          .top-search-products__items__item
            = image_tag product.images[0].img.url
            - if product.status !=  "出品中"
              .top-products__items__item__sold__image
              .top-products__items__item__sold__text SOLD
            .top-search-products__items__item__price
              ¥
              = product.price
            .top-search-products__items__item__name
              = product.name

= render "products/left_side_bar"     
= render "shared/top_footer"

app/views/products/show.html.haml
=render "shared/top_header"

%section.product-box-container.first-container
  %h1.product-name 
    = @product.name
  .product-wording
    『#{@product.name}』は、0回の取引実績を持つ#{@product.user.nickname}さんから出品されました。
    （#{@product.detail.small_category}/#{@product.detail.medium_category}/#{@product.detail.large_category}）の商品で、
    #{@product.origin_area}から#{@product.days_left_send}で発送されます。
  .product-main-content.clearfix
    .product-photo
      .chosen-carousel
        = image_tag @product.images[0].img.url, id:"MainPhoto"
        - if @product.status !=  "出品中"
          .chosen-product-inner__sold__image
          .chosen-product-inner__sold__text SOLD
        .chosen-dots
          - @product.images.each do |image|
            .chosen-dot
              = image_tag image.img.url,class:"ChangePhoto"
    %section.visible-sp
    %table.product-detail-table
      %tbody
        %tr
          %th 出品者
          %td 
            = @product.user.nickname
            .producty
              .product-user-ratings
              .icon-good= fa_icon 'smile-o'
              .icon-number 0
              .product-user-ratings
              .icon-normal= fa_icon 'meh-o'
              .icon-number 0
              .product-user-ratings
              .icon-bad= fa_icon 'frown-o'
              .icon-number 0
        %tr
          %th カテゴリー
          %td
            %span.link
              = link_to "/products/#{@product_parent.id}/category_search_parent" do
                = @product.detail.large_category
            %span.link
              .product-detail-table-sub-category
                - if @product.detail.medium_category.present?
                  = link_to "/products/#{@product_parent.id}/#{@product_child.id}/category_search_child" do
                    %strong ＞ #{@product.detail.medium_category}
            %span.link
              .product-detail-table-sub-sub-category
                - if @product.detail.small_category.present?
                  = link_to "/products/#{@product_parent.id}/#{@product_child.id}/#{@product_grandchild.id}/category_search_grandchild" do
                    %strong ＞ #{@product.detail.small_category}
        %tr
          %th ブランド
          %td #{@product.detail.brand}
        %tr
          %th 商品の状態
          %td #{@product.condition}
        %tr
          %th 配送料の負担
          %td #{@product.delivery_charge}
        %tr
          %th 配送の方法
          %td らくらくメルカリ便
        %tr
          %th 配送元地域
          %td
            %span.link #{@product.origin_area}
        %tr
          %th 発送日の目安
          %td #{@product.days_left_send}
  .product-price-box.text-center
    %span.product-yen.bold ¥
    %span.product-price.bold
      = @product.price
    %span.product-tax (税込)
    %span.product-shipping-fee
      = @product.delivery_charge
    - if (@product.user.id != current_user&.id) && (@product.status == "出品中")
      = link_to "/products/#{@product.id}/user_buying" do
        .product-buy-btn
          購入画面に進む
  .product-description.f14
    %p.product-description-inner
      = @product.discription
  .product-button-container.clearfix
    .product-button-left
      .product-button.product-button-like
        = fa_icon 'heart-o'
        %span いいね!
        %span{'data-num': "like"} 0
      .product-button.product-button-report.clearfix
        = fa_icon 'flag-o'
        %span 不適切な商品の報告
    .product-button-right
      %span.link
        あんしん・あんぜんへの取り組み
- if (@product.user.id == current_user&.id) && (@product.status == "出品中")
  .listing-product-change-box
    = link_to(edit_product_path(@product.id))do
      .listing-product-change-box__edit
        商品の編集
    .listing-product-change-box__or
      or
    .listing-product-change-box__restart
      出品を再開する
    = link_to(product_path(@product.id),{method: "delete"}) do
      .listing-product-change-box__destroy
        この商品を削除する
.product-detail-message
  .message-container

.product-social-media-box
  %ul.social-media-box
    %li
      %a.share-btn
        .icon-facebook= fa_icon 'facebook'
    %li
      %a.share-btn
        .icon-twitter= fa_icon 'twitter'
    %li.social-hidden-product
      .icon-line
        .icon-line= fa_icon 'comment'
    %li
      .share-btn
        .icon-pinterest= fa_icon 'pinterest'

.products-in-user-profile
  %section.products-box-container.clearfix.related-product-column.products-in-user-profile
    %h2.products-box-head
      %span.link #{@product.user.nickname}さんのその他の出品
    .products-box-content.clearfix
    - @user_products.each do |product|
      %section.products-box
        %figure.products-box-photo
          .lazyloaded
          = link_to product_path(product.id) do
            = image_tag product.images[0].img.url
        .products-box-body
          %h3.products-box-name
            = product.name
          .products-box-num
            .products-box-price.font-5
            ¥#{product.price}
            .font-2
              = fa_icon 'heart-o'
              %span 0

  %section.products-box-container.clearfix.related-product-column
    %h2.products-box-head
      %span.link
        #{@product.detail.large_category} その他の商品
    .products-box-content.clearfix
    - @category_products.each do |product|
      %section.products-box
        %figure.products-box-photo
          .lazyloaded
          = link_to product_path(product.id) do
            = image_tag product.images[0].img.url
        .products-box-body
          %h3.products-box-name
            = product.name
          .products-box-num
            .products-box-price.font-5
            ¥#{product.price}
            .font-2
              = fa_icon 'heart-o'
              %span 0

              
%aside.modal{'data-close': "modal", 'data-modal': "report-product"}
  .modal-inner.modal-banner
    .modal-body
      .modal-head.bold 確認
      不適切な商品を報告しますか？
    .clearfix
      .modal-btn.modal-btn-cancel{'data-close': "modal"} キャンセル
      %button.modal-btn.modal-btn-submit はい
%nav.bread-crumbs.pos-bottom
  %ul
    %li{productscope: "", producttype: "http://data-vocabulary.org/Breadcrumb"}
      = link_to "/" do
        %span{productprop: "title"} メルカリ
        %strong ＞
    %li{productscope: "", producttype: "http://data-vocabulary.org/Breadcrumb"}
      %span{productprop: "title"} #{@product.name}

=render "shared/top_footer"